export const appRoutes = {
  login: '/auth/login',
  register: '/auth/register',
  customerTabs: '/(tabs)',
  scan: '/scan',
  nfcDemo: '/nfc-demo',
  guestAnalytics: '/guest-analytics',
  newOrder: '/new-order',
  orderDetail: '/order-detail/[orderId]',
  sales: {
    root: '/sales',
    orders: '/sales/orders',
    newOrder: '/sales/new-order',
    payouts: '/sales/payouts',
    notifications: '/sales/notifications',
    settings: '/sales/settings',
  },
  printer: {
    queue: '/printer/queue',
    newOrder: '/printer/new-order',
    settings: '/printer/settings',
    wages: '/printer/wages',
    notifications: '/printer/notifications',
  },
} as const;
