import React, { useState, useEffect } from 'react';
import { 
  View, 
  Text, 
  StyleSheet, 
  TouchableOpacity, 
  Alert,
  Platform 
} from 'react-native';
import { CameraView, CameraType, useCameraPermissions } from 'expo-camera';
import { router } from 'expo-router';
import { X, FlipHorizontal, Zap, ZapOff } from 'lucide-react-native';
import { 
  parseQRCode, 
  generateAttendanceRecord, 
  validateQRCode,
  parseSecureQRCode,
  validateSecureQRCode,
  getAttendanceMessage,
  formatTime 
} from '@/utils/attendanceUtils';
import { 
  parseGroupQRCode,
  createJoinRequest,
  recordGroupAttendance,
  validateGroupMembership,
  isAttendanceWindowActive,
  getGroupAttendanceMessage,
  getMockGroupMemberships
} from '@/utils/groupQRScanner';
import { GroupInviteQRData, GroupAttendanceQRData } from '@/types/groups';
import { useNotifications } from '@/contexts/NotificationContext';
import { useAuth } from '@/contexts/AuthContext';
import { QRCodeData as SecureQRCodeData, UserInviteNotification, EventInviteNotification } from '@/types/qr';
import { FirebaseService } from '@/services/firebaseService';
import { toNotificationAudience } from '@/utils/authz';

export default function QRScannerScreen() {
  const { addNotification } = useNotifications();
  const { user } = useAuth();
  const [facing, setFacing] = useState<CameraType>('back');
  const [permission, requestPermission] = useCameraPermissions();
  const [scanned, setScanned] = useState(false);
  const [flashEnabled, setFlashEnabled] = useState(false);
  const [isProcessing, setIsProcessing] = useState(false);

  const currentUser = user;

  if (!permission) {
    return (
      <View style={styles.container}>
        <Text style={styles.message}>Loading camera...</Text>
      </View>
    );
  }

  if (!permission.granted) {
    return (
      <View style={styles.container}>
        <View style={styles.permissionContainer}>
          <Text style={styles.message}>Camera access is required to scan QR codes for attendance</Text>
          <TouchableOpacity style={styles.permissionButton} onPress={requestPermission}>
            <Text style={styles.permissionButtonText}>Grant Camera Permission</Text>
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  const handleBarcodeScanned = async ({ type, data }: { type: string; data: string }) => {
    if (scanned || isProcessing) return;
    if (!currentUser) return;
    
    setIsProcessing(true);
    setScanned(true);
    
    try {
      // First try to parse as group QR code
      const groupQRData = parseGroupQRCode(data);
      
      if (groupQRData) {
        await handleGroupQRCode(groupQRData);
        return;
      }
      
      // First try to parse as secure QR code
      const secureQRData = parseSecureQRCode(data);
      
      if (secureQRData) {
        // Handle secure QR codes
        await handleSecureQRCode(secureQRData);
      } else {
        // Try legacy QR code format
        const legacyQRData = parseQRCode(data);
        
        if (!legacyQRData || !validateQRCode(legacyQRData)) {
          Alert.alert(
            'Invalid QR Code ❌',
            'This QR code is not valid or was not generated by this app. Please scan a valid QR code.',
            [
              {
                text: 'Try Again',
                onPress: () => {
                  setScanned(false);
                  setIsProcessing(false);
                },
              },
            ]
          );
          return;
        }
        
        // Handle legacy attendance QR code
        await handleLegacyAttendanceQR(legacyQRData);
      }
    } catch (error) {
      Alert.alert(
        'Error',
        'Failed to process QR code. Please try again.',
        [
          {
            text: 'Try Again',
            onPress: () => {
              setScanned(false);
              setIsProcessing(false);
            },
          },
        ]
      );
    }
  };
  
  const handleGroupQRCode = async (qrData: GroupInviteQRData | GroupAttendanceQRData) => {
    if (qrData.type === 'group_invite') {
      await handleGroupInviteQR(qrData as GroupInviteQRData);
    } else if (qrData.type === 'group_attendance') {
      await handleGroupAttendanceQR(qrData as GroupAttendanceQRData);
    }
  };
  
  const handleGroupInviteQR = async (qrData: GroupInviteQRData) => {
    if (!currentUser) return;
    // Check if group is at capacity
    if (qrData.maxMembers && qrData.currentMembers >= qrData.maxMembers) {
      Alert.alert(
        'Group Full',
        `The group "${qrData.groupName}" has reached its maximum capacity of ${qrData.maxMembers} members.`,
        [
          {
            text: 'OK',
            onPress: () => {
              setScanned(false);
              setIsProcessing(false);
            },
          },
        ]
      );
      return;
    }

    // Create join request
    const joinRequest = createJoinRequest(qrData, currentUser.id, currentUser.email, currentUser.name, currentUser.employeeId);

    // Add notification for user
    addNotification({
      type: 'join_request',
      targetAudience: 'user',
      title: 'Join Request Submitted',
      message: `Your request to join "${qrData.groupName}" has been submitted for approval`,
      isRead: false,
      priority: 'medium',
      metadata: {
        requestId: joinRequest.id,
        organizationName: qrData.groupName,
        adminName: qrData.adminName,
        status: 'pending',
        role: 'user',
      },
    });
    await FirebaseService.createJoinRequest({
      groupId: qrData.groupId,
      groupName: qrData.groupName,
      adminId: qrData.adminId,
      userId: currentUser.id,
      userEmail: currentUser.email,
      userName: currentUser.name,
      employeeId: currentUser.employeeId,
      secretKey: qrData.secretKey,
    });

    Alert.alert(
      '👥 Group Invitation',
      `You've scanned an invite to join:\n\n${qrData.groupName}\n\n${qrData.groupDescription}\n\nAdmin: ${qrData.adminName}\nMembers: ${qrData.currentMembers}${qrData.maxMembers ? `/${qrData.maxMembers}` : ''}\n\nYour join request will be sent to the admin for approval.`,
      [
        {
          text: 'Cancel',
          style: 'cancel',
          onPress: () => {
            setScanned(false);
            setIsProcessing(false);
          },
        },
        {
          text: 'Send Request',
          onPress: () => {
            Alert.alert(
              'Request Sent! 📤',
              `Your join request for "${qrData.groupName}" has been sent to ${qrData.adminName}. You'll be notified when it's processed.`,
              [
                {
                  text: 'OK',
                  onPress: () => {
                    setScanned(false);
                    setIsProcessing(false);
                  },
                },
              ]
            );
            console.log('Group join request:', joinRequest);
          },
        },
      ]
    );
  };
  
  const handleGroupAttendanceQR = async (qrData: GroupAttendanceQRData) => {
    if (!currentUser) return;
    // Get mock group memberships for current user
    const userMemberships = getMockGroupMemberships(currentUser.id);
    
    // Validate group membership
    const membershipValidation = validateGroupMembership(
      qrData.groupId,
      currentUser.id,
      userMemberships
    );
    
    if (!membershipValidation.isMember) {
      Alert.alert(
        'Access Denied ❌',
        membershipValidation.reason || 'You cannot access this group attendance',
        [
          {
            text: 'OK',
            onPress: () => {
              setScanned(false);
              setIsProcessing(false);
            },
          },
        ]
      );
      return;
    }
    
    // Check if attendance window is active
    const windowValidation = isAttendanceWindowActive(qrData.attendanceWindow);
    
    if (!windowValidation.isActive) {
      Alert.alert(
        'Outside Attendance Window ⏰',
        windowValidation.reason || 'Attendance is not available at this time',
        [
          {
            text: 'OK',
            onPress: () => {
              setScanned(false);
              setIsProcessing(false);
            },
          },
        ]
      );
      return;
    }
    
    const attendanceRecord = await FirebaseService.validateAndRecordAttendance(
      currentUser,
      qrData.attendanceId,
      JSON.stringify(qrData)
    );
    
    const currentTime = formatTime(new Date());
    const mappedGroupStatus = attendanceRecord.status === 'Late' ? 'late' : 'present';
    const statusMessage = getGroupAttendanceMessage(mappedGroupStatus, qrData.title);
    
    // Add notification for successful attendance
    addNotification({
      type: 'attendance',
      targetAudience: 'user',
      title: 'Group Attendance Recorded',
      message: `Attendance recorded for "${qrData.title}"`,
      isRead: false,
      priority: 'medium',
      metadata: {
        employeeId: currentUser.employeeId,
        status: 'success',
        location: qrData.location || 'Group Location',
        checkInTime: currentTime,
        attendanceType: 'check_in',
      } as any,
    });
    
    // Show status-specific emoji
    const statusEmoji = attendanceRecord.status === 'Present' ? '✅' : '⚠️';
    
    Alert.alert(
      `Group Attendance Recorded! ${statusEmoji}`,
      `Group: ${qrData.title}\nEmployee: ${currentUser.name}\nID: ${currentUser.employeeId}\nTime: ${currentTime}\nStatus: ${attendanceRecord.status.toUpperCase()}\nLocation: ${qrData.location || 'Group Location'}\n\n${statusMessage}`,
      [
        {
          text: 'Scan Another',
          onPress: () => {
            setScanned(false);
            setIsProcessing(false);
          },
        },
        {
          text: 'Back to Home',
          onPress: () => router.push('/(tabs)/'),
        },
      ]
    );

    console.log('Group Attendance Record:', attendanceRecord);
  };
  
  const handleSecureQRCode = async (qrData: SecureQRCodeData) => {
    switch (qrData.type) {
      case 'attendance':
        await handleAttendanceQR(qrData);
        break;
      case 'user_invite':
        await handleUserInviteQR(qrData);
        break;
      case 'event_invite':
        await handleEventInviteQR(qrData);
        break;
      default:
        throw new Error('Unknown QR code type');
    }
  };
  
  const handleAttendanceQR = async (qrData: any) => {
    if (!currentUser) return;
    // Generate attendance record
    const attendanceRecord = generateAttendanceRecord(
      currentUser.id,
      currentUser.employeeId,
      currentUser.name,
      {
        officeId: qrData.officeId,
        locationName: qrData.locationName,
        timestamp: qrData.createdAt,
        type: 'checkin',
      }
    );

    const currentTime = formatTime(new Date());
    const statusMessage = getAttendanceMessage(attendanceRecord.status);

    // Add notification for successful attendance
    addNotification({
      type: 'attendance',
      targetAudience: toNotificationAudience(currentUser.role),
      title: 'Attendance Recorded',
      message: `Successfully checked in at ${qrData.locationName}`,
      isRead: false,
      priority: 'medium',
      metadata: {
        employeeId: currentUser.employeeId,
        employeeName: currentUser.name,
        status: attendanceRecord.status.toLowerCase() as 'present' | 'late',
        location: qrData.locationName,
        checkInTime: currentTime,
      } as any,
    });
    Alert.alert(
      'Attendance Recorded! ✅',
      `Employee: ${currentUser.name}\nID: ${currentUser.employeeId}\nTime: ${currentTime}\nStatus: ${attendanceRecord.status}\nLocation: ${qrData.locationName}\n\n${statusMessage}`,
      [
        {
          text: 'Scan Another',
          onPress: () => {
            setScanned(false);
            setIsProcessing(false);
          },
        },
        {
          text: 'Back to Home',
          onPress: () => router.push('/(tabs)/'),
        },
      ]
    );

    console.log('Attendance Record:', attendanceRecord);
  };
  
  const handleUserInviteQR = async (qrData: any) => {
    if (!currentUser) return;
    // Add notification for user invite response
    const handleInviteResponse = (accepted: boolean) => {
      addNotification({
        type: 'user_invite',
        targetAudience: toNotificationAudience(currentUser.role),
        title: accepted ? 'Invitation Accepted' : 'Invitation Declined',
        message: `You ${accepted ? 'accepted' : 'declined'} the invitation to join ${qrData.organizationName}`,
        isRead: false,
        priority: 'medium',
        metadata: {
          inviteId: qrData.id,
          userName: currentUser.name,
          userEmail: currentUser.email,
          organizationName: qrData.organizationName,
          status: accepted ? 'approved' : 'declined',
          role: qrData.role,
          requestedAt: new Date().toISOString(),
        } as any,
      });
    };

    Alert.alert(
      '👥 User Invitation',
      `You've been invited to join:\n\n${qrData.organizationName}\n\nInvited by: ${qrData.adminName}\nRole: ${qrData.role.toUpperCase()}\n\nWould you like to accept this invitation?`,
      [
        {
          text: 'Decline',
          style: 'cancel',
          onPress: () => {
            handleInviteResponse(false);
            // Handle decline
            Alert.alert('Invitation Declined', 'You have declined the invitation.');
            setScanned(false);
            setIsProcessing(false);
          },
        },
        {
          text: 'Accept',
          onPress: () => {
            handleInviteResponse(true);
            // Handle accept - in production, this would create user account
            Alert.alert(
              'Invitation Accepted! 🎉',
              `Welcome to ${qrData.organizationName}! Your account will be created shortly.`,
              [
                {
                  text: 'Continue',
                  onPress: () => {
                    setScanned(false);
                    setIsProcessing(false);
                  },
                },
              ]
            );
            console.log('User invite accepted:', qrData);
          },
        },
      ]
    );
  };
  
  const handleEventInviteQR = async (qrData: any) => {
    if (!currentUser) return;
    const eventDateTime = new Date(`${qrData.eventDate}T${qrData.eventTime}`);
    const isExpired = eventDateTime < new Date();
    
    if (isExpired) {
      Alert.alert(
        'Event Expired',
        'This event has already passed.',
        [
          {
            text: 'OK',
            onPress: () => {
              setScanned(false);
              setIsProcessing(false);
            },
          },
        ]
      );
      return;
    }
    
    const participantsText = qrData.maxParticipants 
      ? `\nParticipants: ${qrData.currentParticipants}/${qrData.maxParticipants}`
      : `\nCurrent participants: ${qrData.currentParticipants}`;
    
    const handleEventResponse = (joined: boolean) => {
      addNotification({
        type: 'event',
        targetAudience: toNotificationAudience(currentUser.role),
        title: joined ? 'Event Joined' : 'Event Declined',
        message: `You ${joined ? 'joined' : 'declined'} the event "${qrData.eventName}"`,
        isRead: false,
        priority: 'low',
        metadata: {
          eventId: qrData.eventId,
          eventName: qrData.eventName,
          eventDate: qrData.eventDate,
          eventTime: qrData.eventTime,
          participantCount: qrData.currentParticipants + (joined ? 1 : 0),
          maxParticipants: qrData.maxParticipants,
          rsvpStatus: joined ? 'accepted' : 'declined',
          location: qrData.location,
          eventDescription: qrData.eventDescription || qrData.eventName,
          invitationType: 'invitation',
          currentParticipants: qrData.currentParticipants + (joined ? 1 : 0),
        } as any,
      });
    };

    Alert.alert(
      '📅 Event Invitation',
      `${qrData.eventName}\n\n${qrData.eventDescription}\n\nDate: ${qrData.eventDate}\nTime: ${qrData.eventTime}\nLocation: ${qrData.location}${participantsText}\n\nWould you like to join this event?`,
      [
        {
          text: 'Decline',
          style: 'cancel',
          onPress: () => {
            handleEventResponse(false);
            Alert.alert('Event Declined', 'You have declined the event invitation.');
            setScanned(false);
            setIsProcessing(false);
          },
        },
        {
          text: 'Join Event',
          onPress: () => {
            // Check if event is full
            if (qrData.maxParticipants && qrData.currentParticipants >= qrData.maxParticipants) {
              Alert.alert(
                'Event Full',
                'Sorry, this event has reached maximum capacity.',
                [
                  {
                    text: 'OK',
                    onPress: () => {
                      setScanned(false);
                      setIsProcessing(false);
                    },
                  },
                ]
              );
              return;
            }
            
            handleEventResponse(true);
            Alert.alert(
              'Event Joined! 🎉',
              `You have successfully joined "${qrData.eventName}". You'll receive a reminder before the event.`,
              [
                {
                  text: 'Great!',
                  onPress: () => {
                    setScanned(false);
                    setIsProcessing(false);
                  },
                },
              ]
            );
            console.log('Event joined:', qrData);
          },
        },
      ]
    );
  };
  
  const handleLegacyAttendanceQR = async (qrData: any) => {
      if (!currentUser) return;
      // Generate attendance record
      const attendanceRecord = generateAttendanceRecord(
        currentUser.id,
        currentUser.employeeId,
        currentUser.name,
        qrData
      );

      // Get current time for display
      const currentTime = formatTime(new Date());
      const statusMessage = getAttendanceMessage(attendanceRecord.status);

      // Show success message with attendance details
      Alert.alert(
        'Attendance Recorded! ✅',
        `Employee: ${currentUser.name}\nID: ${currentUser.employeeId}\nTime: ${currentTime}\nStatus: ${attendanceRecord.status}\nLocation: ${qrData.locationName}\n\n${statusMessage}`,
        [
          {
            text: 'Scan Another',
            onPress: () => {
              setScanned(false);
              setIsProcessing(false);
            },
          },
          {
            text: 'Back to Home',
            onPress: () => router.push('/(tabs)/'),
          },
        ]
      );

      // Here you would typically save to database
      console.log('Attendance Record:', attendanceRecord);
      
  };

  const toggleCameraFacing = () => {
    setFacing(current => (current === 'back' ? 'front' : 'back'));
  };

  const toggleFlash = () => {
    setFlashEnabled(!flashEnabled);
  };

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity style={styles.closeButton} onPress={() => router.back()}>
          <X size={24} color="#ffffff" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Scan QR Code</Text>
        <View style={styles.placeholder} />
      </View>

      <View style={styles.cameraContainer}>
        <CameraView
          style={styles.camera}
          facing={facing}
          enableTorch={flashEnabled}
          onBarcodeScanned={scanned ? undefined : handleBarcodeScanned}
          barcodeScannerSettings={{
            barcodeTypes: ['qr'],
          }}
        >
          <View style={styles.overlay}>
            <View style={styles.scanArea}>
              <View style={[styles.corner, styles.topLeft]} />
              <View style={[styles.corner, styles.topRight]} />
              <View style={[styles.corner, styles.bottomLeft]} />
              <View style={[styles.corner, styles.bottomRight]} />
              
              {isProcessing && (
                <View style={styles.processingOverlay}>
                  <Text style={styles.processingText}>Processing QR Code...</Text>
                </View>
              )}
            </View>
            
            <Text style={styles.instructionText}>
              Position QR code within the frame to scan
            </Text>
          </View>

          <View style={styles.controls}>
            {Platform.OS !== 'web' && (
              <TouchableOpacity 
                style={[styles.controlButton, flashEnabled && styles.controlButtonActive]} 
                onPress={toggleFlash}
              >
                {flashEnabled ? (
                  <Zap size={24} color="#ffffff" />
                ) : (
                  <ZapOff size={24} color="#ffffff" />
                )}
              </TouchableOpacity>
            )}
            
            <TouchableOpacity style={styles.controlButton} onPress={toggleCameraFacing}>
              <FlipHorizontal size={24} color="#ffffff" />
            </TouchableOpacity>
          </View>
        </CameraView>
      </View>

      <View style={styles.instructions}>
        <Text style={styles.instructionMainText}>
          Position any valid QR code within the frame
        </Text>
        <Text style={styles.instructionSubText}>
          Current Time: {formatTime(new Date())} • Supports: Groups, Attendance, Invites, Events
        </Text>
        {scanned && !isProcessing && (
          <TouchableOpacity 
            style={styles.scanAgainButton} 
            onPress={() => {
              setScanned(false);
              setIsProcessing(false);
            }}
          >
            <Text style={styles.scanAgainText}>Tap to Scan Again</Text>
          </TouchableOpacity>
        )}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  header: {
    backgroundColor: '#2563eb',
    paddingVertical: 12,
    paddingHorizontal: 16,
    paddingTop: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#1d4ed8',
  },
  closeButton: {
    padding: 8,
  },
  headerTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '400',
  },
  placeholder: {
    width: 40,
  },
  permissionContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#2563eb',
  },
  message: {
    color: '#ffffff',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
  },
  permissionButton: {
    backgroundColor: '#1d4ed8',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  permissionButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  cameraContainer: {
    flex: 1,
  },
  camera: {
    flex: 1,
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scanArea: {
    width: 280,
    height: 280,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  corner: {
    position: 'absolute',
    width: 50,
    height: 50,
    borderColor: '#ffffff',
    borderWidth: 5,
  },
  topLeft: {
    top: 0,
    left: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
  },
  topRight: {
    top: 0,
    right: 0,
    borderLeftWidth: 0,
    borderBottomWidth: 0,
  },
  bottomLeft: {
    bottom: 0,
    left: 0,
    borderRightWidth: 0,
    borderTopWidth: 0,
  },
  bottomRight: {
    bottom: 0,
    right: 0,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  processingOverlay: {
    position: 'absolute',
    backgroundColor: 'rgba(37, 99, 235, 0.9)',
    borderRadius: 8,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  processingText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
  },
  instructionText: {
    color: '#ffffff',
    fontSize: 18,
    textAlign: 'center',
    marginTop: 40,
    paddingHorizontal: 20,
    fontWeight: '700',
  },
  controls: {
    position: 'absolute',
    bottom: 120,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 40,
  },
  controlButton: {
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: 30,
    padding: 15,
    borderWidth: 3,
    borderColor: 'transparent',
  },
  controlButtonActive: {
    borderColor: '#ffffff',
    backgroundColor: 'rgba(37, 99, 235, 0.8)',
  },
  instructions: {
    backgroundColor: '#2563eb',
    padding: 20,
    alignItems: 'center',
  },
  instructionMainText: {
    color: '#ffffff',
    fontSize: 16,
    textAlign: 'center',
    fontWeight: '800',
  },
  instructionSubText: {
    color: '#93c5fd',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 4,
    fontWeight: '500',
  },
  scanAgainButton: {
    backgroundColor: '#1d4ed8',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 6,
    marginTop: 12,
  },
  scanAgainText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
});
